ALTER TABLE rooms ADD COLUMN image_key TEXT;
ALTER TABLE rooms ADD COLUMN image_name TEXT;
ALTER TABLE rooms ADD COLUMN image_type TEXT;
ALTER TABLE rooms ADD COLUMN image_size INTEGER;

CREATE TABLE IF NOT EXISTS admin_rate_limits (
  ip TEXT PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 0,
  window_start INTEGER NOT NULL
);
