import { clientIp, error, json } from "./_shared.js";
const ID=/^[A-Za-z0-9_-]{1,64}$/; const TYPES=new Set(["chat","camera","feed"]); const IMAGE_TYPES=new Set(["image/jpeg","image/png","image/webp","image/gif"]); const MAX=25*1024*1024;
const clean=(v,n)=>typeof v==="string"?v.trim().slice(0,n):"";
function eq(a,b){if(typeof a!=="string"||typeof b!=="string"||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function auth(request,env){
 if(!env.ADMIN_PASSWORD)return {response:error("ADMIN_NOT_CONFIGURED","ADMIN_PASSWORD를 설정하세요.",503)};
 const ip=clientIp(request),now=Date.now(),row=await env.DB.prepare(`SELECT attempts,window_start FROM admin_rate_limits WHERE ip=?`).bind(ip).first();
 if(row&&now-Number(row.window_start)<600000&&Number(row.attempts)>=10)return {response:error("RATE_LIMITED","로그인 시도가 너무 많습니다. 10분 후 다시 시도하세요.",429)};
 const supplied=request.headers.get("X-Admin-Password")||"";
 if(!eq(env.ADMIN_PASSWORD,supplied)){
  await env.DB.prepare(`INSERT INTO admin_rate_limits(ip,attempts,window_start) VALUES(?,1,?) ON CONFLICT(ip) DO UPDATE SET attempts=CASE WHEN ?-window_start>=600000 THEN 1 ELSE attempts+1 END,window_start=CASE WHEN ?-window_start>=600000 THEN ? ELSE window_start END`).bind(ip,now,now,now,now).run();
  return {response:error("UNAUTHORIZED","관리자 비밀번호가 올바르지 않습니다.",401)};
 }
 await env.DB.prepare(`DELETE FROM admin_rate_limits WHERE ip=?`).bind(ip).run(); return {ip};
}
function randomLikeCount(){const r=Math.random();if(r<.6)return Math.floor(Math.random()*420)+80;if(r<.9)return Math.floor(Math.random()*1500)+500;return Math.floor(Math.random()*3000)+2000}
function randomId(){const b=new Uint8Array(16);crypto.getRandomValues(b);return "room-"+btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function safeName(v){return clean(v,120).replace(/[^\p{L}\p{N}._ -]+/gu,"_").trim()||"image"}
async function parse(request){const ct=request.headers.get("Content-Type")||"";if(ct.includes("multipart/form-data")){const f=await request.formData();return {data:Object.fromEntries([...f.entries()].filter(([k,v])=>!(v instanceof File))),images:f.getAll("images")}}try{return {data:await request.json(),images:[]}}catch{return null}}
async function storeImages(env,roomId,files){
 const valid=files.filter(x=>x instanceof File&&x.size>0); if(valid.length>5)throw new Error("TOO_MANY_IMAGES"); if(valid.length&&!env.IMAGES)throw new Error("R2_NOT_CONFIGURED");
 const stored=[]; for(let i=0;i<valid.length;i++){const file=valid[i];if(!IMAGE_TYPES.has(file.type))throw new Error("INVALID_IMAGE_TYPE");if(file.size>MAX)throw new Error("IMAGE_TOO_LARGE");const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[file.type];const key=`rooms/${roomId}/${crypto.randomUUID()}.${ext}`;await env.IMAGES.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public,max-age=31536000,immutable"},customMetadata:{roomId,originalName:safeName(file.name)}});stored.push({key,name:safeName(file.name),type:file.type,size:file.size,sort:i})}return stored;
}
function imageError(c){const m={TOO_MANY_IMAGES:["TOO_MANY_IMAGES","이미지는 최대 5장까지 첨부할 수 있습니다.",400],R2_NOT_CONFIGURED:["R2_NOT_CONFIGURED","R2 바인딩 IMAGES가 없습니다.",503],INVALID_IMAGE_TYPE:["INVALID_IMAGE_TYPE","JPG, PNG, WEBP, GIF만 가능합니다.",400],IMAGE_TOO_LARGE:["IMAGE_TOO_LARGE","이미지 한 장은 최대 25MB입니다.",413]}[c?.message];return m?error(...m):null}
export async function onRequestGet(context){const a=await auth(context.request,context.env);if(a.response)return a.response;try{const rooms=await context.env.DB.prepare(`SELECT r.id,r.title,r.room_type,r.publisher_name,r.owner_name,r.message_limit,r.message_count,r.status,r.created_at,(SELECT COUNT(*) FROM room_images i WHERE i.room_id=r.id) image_count FROM rooms r ORDER BY r.created_at DESC LIMIT 500`).all();return json({success:true,rooms:rooms.results||[]})}catch(c){console.error(c);return error("SERVER_ERROR","목록을 불러오지 못했습니다.",500)}}
export async function onRequestPost(context){const a=await auth(context.request,context.env);if(a.response)return a.response;const p=await parse(context.request);if(!p)return error("INVALID_INPUT","요청 형식이 올바르지 않습니다.",400);const d=p.data||{},id=clean(d.id,64)||randomId(),title=clean(d.title,80),type=clean(d.roomType,20)||"chat",publisher=clean(d.publisherName,40)||"이미지 게시자",owner=clean(d.ownerName,40)||"게시판 주인",limit=Number(d.messageLimit||30);
 if(!ID.test(id)||!title||!TYPES.has(type))return error("INVALID_INPUT","방 정보가 올바르지 않습니다.",400);if(!Number.isInteger(limit)||limit<1||limit>1000)return error("INVALID_LIMIT","제한은 1~1000 사이여야 합니다.",400);
 const config={displayName:clean(d.displayName,40)||"오늘의 기록",userId:clean(d.userId,40)||"@daily_moment",caption:clean(d.caption,500),likeCount:randomLikeCount(),allowDownload:d.allowDownload!=="false"};let stored=[];
 try{if(await context.env.DB.prepare(`SELECT id FROM rooms WHERE id=?`).bind(id).first())return error("DUPLICATE","이미 사용 중인 코드입니다.",409);stored=await storeImages(context.env,id,p.images||[]);if(type==="chat"&&limit<stored.length)return error("LIMIT_BELOW_IMAGE_COUNT",`채팅 제한은 첨부 이미지 수(${stored.length}) 이상이어야 합니다.`,400);await context.env.DB.prepare(`INSERT INTO rooms(id,title,room_type,room_config,publisher_name,owner_name,publisher_avatar,owner_avatar,message_limit,message_count,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,0,'open',?)`).bind(id,title,type,JSON.stringify(config),publisher,owner,"/assets/default-avatar.svg","/assets/default-avatar.svg",limit,new Date().toISOString()).run();for(const x of stored)await context.env.DB.prepare(`INSERT INTO room_images(room_id,image_key,image_name,image_type,image_size,sort_order) VALUES(?,?,?,?,?,?)`).bind(id,x.key,x.name,x.type,x.size,x.sort).run();return json({success:true,room:{id,title,room_type:type}},201)}catch(c){for(const x of stored)await context.env.IMAGES?.delete(x.key).catch(()=>{});const ie=imageError(c);if(ie)return ie;console.error(c);return error("SERVER_ERROR","방을 생성하지 못했습니다.",500)}}
export async function onRequestPatch(context){const a=await auth(context.request,context.env);if(a.response)return a.response;const p=await parse(context.request),d=p?.data||{},roomId=clean(d.roomId,64);try{if(d.action==="updateLimit"){const n=Number(d.messageLimit);if(!Number.isInteger(n)||n<1||n>1000)return error("INVALID_LIMIT","제한은 1~1000 사이여야 합니다.",400);await context.env.DB.prepare(`UPDATE rooms SET message_limit=?,status=CASE WHEN message_count<? THEN 'open' ELSE 'closed' END WHERE id=?`).bind(n,n,roomId).run();return json({success:true})}if(d.action==="reset"){await context.env.DB.batch([context.env.DB.prepare(`DELETE FROM messages WHERE room_id=?`).bind(roomId),context.env.DB.prepare(`UPDATE rooms SET message_count=0,status='open' WHERE id=?`).bind(roomId)]);return json({success:true})}return error("UNKNOWN_ACTION","지원하지 않는 작업입니다.",400)}catch(c){console.error(c);return error("SERVER_ERROR","변경하지 못했습니다.",500)}}
export async function onRequestDelete(context){const a=await auth(context.request,context.env);if(a.response)return a.response;const p=await parse(context.request),roomId=clean(p?.data?.roomId,64);try{const imgs=await context.env.DB.prepare(`SELECT image_key FROM room_images WHERE room_id=?`).bind(roomId).all();await context.env.DB.batch([context.env.DB.prepare(`DELETE FROM messages WHERE room_id=?`).bind(roomId),context.env.DB.prepare(`DELETE FROM room_images WHERE room_id=?`).bind(roomId),context.env.DB.prepare(`DELETE FROM rooms WHERE id=?`).bind(roomId)]);for(const x of imgs.results||[])await context.env.IMAGES?.delete(x.image_key).catch(()=>{});return json({success:true})}catch(c){console.error(c);return error("SERVER_ERROR","삭제하지 못했습니다.",500)}}
